baseURL: https://www.ivansalinasss.dev/
languageCode: es-py
title: IvanSalinasss
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
defaultContentLanguage: es
languages:
  es:
    languageName: Español
    weight: 1
  en:
    languageName: English
    weight: 2

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # background image of the landing page
  background: "images/background.jpg"
  
  # GitHub repo URL of your site
  gitRepo: https://github.com/ivansalinasss/web-personal.git

  # themes
  darkMode:
    enable: true
    provider: darkreader
    default: system

  # The inverted logo will be used in the initial transparent navbar and
  # the main logo will be used in the non-transparent navbar.
  logo:
    main: images/ivan.png
    favicon: images/favicon.svg

  # disable Newsletter
  newsletter:
    enable: false